first changes
Azure-Samples/explore-iot-operations pull request #83
Opened 2024-08-14 16:58 UTC by olivakar

Adds a C# app to read data from HTTP endpoint.
There is a dummy rest service for testing purposes. I have kept that code for now (ideally not to be included)

2024-08-15 04:27 UTC, varunpuranik commented on samples/context-app-csharp/console-app-secret.yaml
> +  password: YWxvaG9tb3Jh  # Base64 encoded password
Replace with stubs

2024-08-15 04:28 UTC, varunpuranik commented on samples/context-app-csharp/e4k-simple.yaml
> +## Simple deployment of the broker. This is a minimal configuration to get the broker running.
This file should not be checked in (esp with 1883 port). We should point to official documentation for MQ installation. (also don't call it E4K)

2024-08-15 04:29 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            StateStoreClient stateStoreClient = new(mqttClient);
Use Interface instead..

2024-08-15 04:30 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            await retrieveAndStore(dataRetriever, stateStoreClient);
1. PascalCase for method names
2. Suggest calling it something like PopulateContextualDataLoop or so..

2024-08-15 04:31 UTC, varunpuranik commented on samples/context-app-csharp/DummyService/Dockerfile
Since the sample is dotnet, can we write the service in dotnet as well? 
It can be an ASP.net core web api

2024-08-15 04:33 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            }
Remove

2024-08-15 04:34 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            MqttConnectionSettings connectionSettings = new(host) { TcpPort = 1883, ClientId = "someClientId", UseTls = false };
Should be config.. 
ClientId should be default, if not passed in

2024-08-15 04:37 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/IDataRetriever.cs
> +        Task<string> RetrieveDataAsync(RetrievalConfig userConfig);
I don't think you can (or should) make the RetrievalConfig and auth generic. It will have to be endpoint specific. So better keep it that way. 
One way to do that is to pass in the retrievalConfig not in RetrieveData, but in the ctor of the actual DataRetriever.

2024-08-15 04:38 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            await retrieveAndStore(dataRetriever, stateStoreClient);
A better structure seems to be: 
- The loop to get data and store it in DSS should be a separate class which is generic in the source of the data. 
- Main can then create the right source and pass it in to the class.

2024-08-15 20:35 UTC, abhipsaMisra commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            _logger = loggerFactory.CreateLogger<Program>();
Is there a reason for using a ServiceCollection other than creating a logger? Are you using some background runner/service template that mandates this? I ask because I don't see a reference to this service provider being used anywhere else, but it could be that I missed something.

If not, then you might be able to get this done through the simplified format from [here](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#get-started):
```c#
using Microsoft.Extensions.Logging;

using ILoggerFactory factory = LoggerFactory.Create(builder => builder.AddConsole());
ILogger logger = factory.CreateLogger("Program");
logger.LogInformation("Hello World! Logging is {Description}.", "fun");
```

2024-08-15 20:35 UTC, abhipsaMisra commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            var mqttClient = await SetupMqttClient();
nit: Add `Async` suffix to async method names. This helps establish to the caller that the method being called is an awaitable method.

2024-08-15 20:35 UTC, abhipsaMisra commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            var mqttClient = await SetupMqttClient();
This is an IAsyncDisposable type so make sure you dispose it once you're done with it.
You can use the `await using` syntax explained [here](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#using-async-disposable):

```c#
await using MqttSessionClient mqttClient = await SetupMqttClient();
```

2024-08-15 20:35 UTC, abhipsaMisra commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            string connectionStringOrBaseUrl = "http://my-backend-api-s.default.svc.cluster.local";
nit: is this supposed to always be hardcoded for the purpose of this sample? A comment here explaining what this endpoint points to would be useful.

2024-08-15 20:35 UTC, abhipsaMisra commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            var mqttClient = await SetupMqttClient();
I see that the StateStoreClient is actually disposing the mqttClient, so you are actually handling the disposal through the explicit StateStoreClient disposal that you have in `retrieveAndStore` below.

For the purpose of a sample, I'd recommend 2 things - 
- Keep the disposal of the StateStoreClient outside of a method that accepts it as a param, and instead leave it in `main` itself. It will help improve readability plus more importantly also help aid future changes to the code by not hiding the disposal within a called method somewhere else. The way we have it today, I could add another method call after the call to `retrieveAndStore` and pass it the StateStoreClient, and I'll end up with an ObjectDisposedException.
- Add a comment to the MqttClient creation above that highlights that its disposable is being handled by the StateStoreClient. On that note, what happens if I dispose the MqttClient explicitly anyway? Is it a no-op when the StateStoreClient tries it dispose it again?

2024-08-15 20:35 UTC, abhipsaMisra commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            await retrieveAndStore(dataRetriever, stateStoreClient);
dataRetriever needs to be disposed as well.

2024-08-16 20:18 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            string connectionStringOrBaseUrl = "http://my-backend-api-s.default.svc.cluster.local";
no, should be config.

2024-08-16 20:18 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/Program.cs
> +            string connectionStringOrBaseUrl = "http://my-backend-api-s.default.svc.cluster.local";
ConfigMap?

2024-08-19 02:41 UTC, olivakar commented on samples/context-app-csharp/DummyService/Dockerfile
Spoke to Udbhav. This is not needed as far as I understand.

2024-08-19 06:39 UTC, varunpuranik commented on samples/context-app-csharp/DummyService/Dockerfile
Not sure I follow - what service will the sample test against? 
@udtri - what is your idea here?

2024-08-19 16:53 UTC, udtri commented on samples/context-app-csharp/DummyService/Dockerfile
I think we should prioritize based on importance- 
1. **Complete the HTTP endpoint retrieval service.** In most cases, the Kubernetes (K8S) cluster will be available for testing against a public request and response service, such as (https://httpbin.org/), or they may already have a designated endpoint in place for testing.
2. **Have the first version of the SQL server query service ready.**
3. **Build first-party (1P) testing samples for the HTTP endpoint.**

2024-08-20 05:50 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/HttpBasicAuth.cs
> +        //        }
why commented out?

2024-08-20 05:57 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS.sln
Can you pls apply dotnet code styling to this project? It would be good to have consistent code styling throughout.

2024-08-20 05:57 UTC, varunpuranik approved these changes

2024-08-20 18:32 UTC, timtay-microsoft commented on samples/context-app-csharp/ContextAppForDSS/ContextualDataOperation.cs
> +                        _logger.LogError("Error retrieving or storing data: " + e.Message);
```suggestion
                        _logger.LogError(e, "Error retrieving or storing data");
```

2024-08-20 18:34 UTC, timtay-microsoft commented on samples/context-app-csharp/ContextAppForDSS/ContextualDataOperation.cs
> +            IStateStoreClient stateStoreClient = new StateStoreClient(mqttClient);
```suggestion
            await using IStateStoreClient stateStoreClient = new StateStoreClient(mqttClient);
```

This will automatically close and dispose this object once it leaves scope

2024-08-20 18:34 UTC, timtay-microsoft commented on samples/context-app-csharp/ContextAppForDSS/ContextualDataOperation.cs
> +                await stateStoreClient.DisposeAsync(true);
If you use the "await using" keywords when creating this client, you can remove this line

2024-08-20 18:37 UTC, timtay-microsoft commented on samples/context-app-csharp/ContextAppForDSS/ContextualDataOperation.cs
> +                _dataRetriever.Dispose();
Typically, a disposable object that is passed in via constructor is only disposed when the class itself is disposed. That would allow for repeated calls to this method.

I'd refactor to something like:

```csharp
internal class ContextualDataOperation : IDisposable
{
    // Other class methods
    
    public void Dispose()
    {
        _dataRetriever.Dispose();
    }
}
```

2024-08-20 18:44 UTC, timtay-microsoft commented on samples/context-app-csharp/ContextAppForDSS.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
nit: The other .NET projects in this repo only define a .csproj (and no .sln file)

Additionally, they refer to the language as "dotnet" (and not "csharp") in the folder structure like "mqtt-client-dotnet"

2024-08-20 18:52 UTC, timtay-microsoft commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +	Note: Replace `my-registry` with the chosen Docker registry.
If you are interested, you can setup a local docker registry and skip having to create an ACR or similar registry. We do this in the mqtt-patterns repo for a few images:

Create the local registry and attach it to a newly created cluster:
```
k3d registry create registry.localhost --port 5500
k3d cluster create -p '1883:1883@loadbalancer' -p '8883:8883@loadbalancer' --registry-use k3d-registry.localhost:5500
```

Publish a docker image to that image:
```
dotnet publish /t:PublishContainer tools/schema-registry/src/Akri.Mq.SchemaRegistry.Host/Akri.Mq.SchemaRegistry.Host.csproj /p:ContainerRegistry=localhost:5500
```

I'm not sure if there is a similar command for publishing a node.js service to the k8s registry, but it could be worth looking into

2024-08-20 18:54 UTC, timtay-microsoft commented on samples/context-app-csharp/ContextAppForDSS/SqlDataRetriever .cs
> +            throw new NotImplementedException();
I'm guessing this is intentional, so you might want to include an error message like

```suggestion
            throw new NotImplementedException("SQL data retrieval is not implemented for simplicity of this sample");
```

2024-08-20 22:49 UTC, olivakar commented on samples/context-app-csharp/ContextAppForDSS/HttpBasicAuth.cs
> +        //        }
file was deleted and does not exist

2024-08-20 23:45 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
Pls move this to the context-app-csharp folder

2024-08-20 23:47 UTC, varunpuranik commented on samples/context-app-csharp/ContextAppForDSS/HttpBasicAuth.cs
> +        //        }
sorry, which file is deleted?

2024-08-20 23:53 UTC, ryanwinter commented
Add the Microsoft copyright header to all relevant files

2024-08-21 00:30 UTC, ryanwinter requested changes

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +		Replace thees values in the above file with the base 64 encoded value.
"thees" replace with "the"
base 64 replace with base64

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +﻿# Steps to create a Context App for DSS
Change header to "Contextual app for state store"

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +This application reads from a endpoint that could be either a HTTP endpoint or a Sql endpoint and
SQL

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +inserts the data to DSS which is running as a part of the MQ broker. The appllication has 2 parts for now:
- remove new line.
- Also use "state store" instead of DSS and "MQTT broker" instead of MQ broker.
- application spelling.
- Remove "for now:"

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +The service has been dockerized and can be deployed to Kubernetes.
containerized

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +Currently this service works on username and password authentication.
"on" replace "using"

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +1. Navigate to the `DummyService` directory`
extra ` at end of line

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +3. Push the Docker image to the chosen Docker registry by running the following command:
"Docker image" replace with "container image"
"docker registry" replace with "container registry"

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +2. Build the Docker image using the following command with:
Build the container image.

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +	Note: Replace `my-registry` with the chosen Docker registry.
You can also push the image directly into the k3d cluster and skip having to create a local registry :)

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +	```bash
Add the kubectl command for getting logs

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +	- `console-app-secret.yaml` : This contains base 64 encoded username and password for the Node.js service. Base 64 encoding can be done using the following command:
base64 not "base 64"

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +
Add "type", "required" and "default value" in table format.

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +	docker build -t my-registry/my-context-app .
I would probably use [dotnet publish](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0) to create the container.

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +4. Dockerize the application by running the following command.
Containerize

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/ContextAppForDSS/ReadMe.md
> +7. On the logs of the pod, the following message should be seen with regular intervals:
Add kubectl log command

2024-08-21 00:30 UTC, ryanwinter commented on samples/context-app-csharp/Dockerfile
> +FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
I think replace with dotnet publish so we dont have to maintain the Docker file

2024-08-21 00:55 UTC, olivakar commented on samples/context-app-csharp/ContextAppForDSS/HttpBasicAuth.cs
> +        //        }
sorry my bad. I thought this is a basic auth strategy file i had before......removed commented code

2024-08-21 02:37 UTC, timtay-microsoft commented on samples/context-app-dotnet/ContextAppForDSS.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Were you unable to remove the .sln file for some reason?

2024-08-21 02:39 UTC, timtay-microsoft commented on samples/context-app-dotnet/ContextAppForDSS/Program.cs
> +            IDataRetriever dataRetriever = DataRetrieverFactory.CreateDataRetriever(dataSourceType, parameters);
```suggestion
            using IDataRetriever dataRetriever = DataRetrieverFactory.CreateDataRetriever(dataSourceType, parameters);
```

2024-08-21 02:40 UTC, timtay-microsoft commented on samples/context-app-dotnet/ReadMe.md
> +   Note: Replace `my-registry` with the chosen container registry.
It might be easier to just have the entire readme assume the user is using the local container registry

2024-08-21 02:40 UTC, timtay-microsoft approved these changes

2024-08-21 04:40 UTC, merged