Ok/tls certs
Azure-Samples/explore-iot-operations pull request #86
Opened 2024-08-24 19:34 UTC by olivakar

2024-08-25 19:48 UTC, ryanwinter requested changes

2024-08-25 19:48 UTC, ryanwinter commented on samples/context-app-dotnet/ContextAppForDSS/ContextualDataOperation.cs
> +using Akri.Mqtt.MqttNetAdapter.Session;
What this adapter? Is this the MqttNet abstraction? Is this how Sessions have to be constructed now?

2024-08-25 19:48 UTC, ryanwinter commented on samples/context-app-dotnet/ContextAppForDSS/ContextualDataOperation.cs
> +                bool hasClientCertKey = !string.IsNullOrEmpty(_parameters["ClientCertKeyFilePath"]) && File.Exists(_parameters["ClientCertKeyFilePath"]);
The naming is a bit confusing for me, but also I'm constantly confused about what to call the two components.

Maybe something like `hasClientPublicCert` and `hasClientPrivateKey`? Does that even make sense?

2024-08-25 19:48 UTC, ryanwinter commented on samples/context-app-dotnet/ContextAppForDSS/ContextualDataOperation.cs
> +                if (hasSatToken)
So we are saying that if the SAT key is set, then it will use SAT, regardless of whether they have also set the x509 cert settings.

I am wondering if an explicit setting for the auth type would be better, but then this could require a configuration that takes a enum for "x509" or "sat" and I dont know if config can do enums, in which case its a string, in which case you then have to deal with making sure the customer puts the right string in there which is possibly worse.

2024-08-25 19:48 UTC, ryanwinter commented on samples/context-app-dotnet/ContextAppForDSS/ContextualDataOperation.cs
> +                    connectionSettings = new(host) { TcpPort = 8883, ClientId = clientId, UseTls = true, CaFile = caFilePath, CertFile = clientCertFile, KeyFile = clientKeyFile, KeyFilePassword = key
We definitly need port configuration (both TLS and non-TLS modes). The defaults should definitly be 1883 and 8883 depending on whether they have TLS setup though. But this is configurable at the MQ side so we have to assume customer may change this.

2024-08-25 19:48 UTC, ryanwinter commented on samples/context-app-dotnet/ContextAppForDSS/ContextualDataOperation.cs
> +                    throw new InvalidOperationException("TLS is enabled but no authentication method is set. Please ensure either SAT token or both Client Cert and Client Key files are set.");
TLS without Auth is a valid configuration, probably not recommended to have AUTH disabled but its possible. TLS would just require the server cert to be provided.

2024-08-25 19:48 UTC, ryanwinter commented on samples/context-app-dotnet/ReadMe.md
> +kubectl create secret generic sat-token-secret --from-literal=token=$(kubectl create token default --duration=8760h --audience=aio-mq)
does this need to be in a specific namespace?

2024-08-25 19:48 UTC, ryanwinter commented on samples/context-app-dotnet/ReadMe.md
> +| `SAT_TOKEN_PATH`           | The path to the SAT token for secure authentication.               | string    | None                  | Yes (if TLS is used)                                  | sat-tok
Nit, and we should just align with whatever MQ uses here, but SAT stands for Service acount token, so this would be "service account token token path" :)

2024-08-25 19:48 UTC, ryanwinter commented on samples/context-app-dotnet/ReadMe.md
> +        docker push k3d-registry.localhost:5500/context-app-for-dss:latest
extra indent

2024-08-25 20:17 UTC, olivakar commented on samples/context-app-dotnet/ContextAppForDSS/ContextualDataOperation.cs
> +using Akri.Mqtt.MqttNetAdapter.Session;
The session client recently changed packages, so I had to add a dependency on the MQTTnet adapter

2024-08-25 20:18 UTC, olivakar commented on samples/context-app-dotnet/ReadMe.md
> +kubectl create secret generic sat-token-secret --from-literal=token=$(kubectl create token default --duration=8760h --audience=aio-mq)
Everything is a default namespace and can be in a default namespace with a default service account.

2024-08-26 17:00 UTC, olivakar commented on samples/context-app-dotnet/ContextAppForDSS/ContextualDataOperation.cs
> +                if (hasSatToken)
Yes I am checking for SAT first.  As of now whatever we set in the deployment file will be taken for authentication. if an enum i s needed we can do that. With helm however it needs to be a choice.

2024-08-26 17:10 UTC, olivakar commented on samples/context-app-dotnet/ReadMe.md
> +| `SAT_TOKEN_PATH`           | The path to the SAT token for secure authentication.               | string    | None                  | Yes (if TLS is used)                                  | sat-tok
I guess you referred to the description.

2024-08-26 17:33 UTC, olivakar commented on samples/context-app-dotnet/ContextAppForDSS/ContextualDataOperation.cs
> +                    throw new InvalidOperationException("TLS is enabled but no authentication method is set. Please ensure either SAT token or both Client Cert and Client Key files are set.");
looking into this but not doing it in this PR coz there are many combos and we are seeing if it is possible to pass in a generic one without so many validations.

2024-08-26 18:59 UTC, timtay-microsoft approved these changes

2024-08-26 19:22 UTC, merged